### ISSUE TITLE
Проблемы с implement

### ISSUE THREAD

**Issue by borisovish** [xxxcoltxxx/grid-laravel#14]
Добрый день!

Хороший клас он меня очень заинтересовал, но периодически при его использовании налетаю на ошибку:
App\GridDataProviders\UsersDataProvider cannot implement Paramonov\Grid\GridDataProvider - it is not an interface

Подскажите в какую степь смотреть, я в MVC не сильно хорошо разбираюсь. 
Заранее благодарю.

**Comment by xxxcoltxxx** [comment]
Вместо implements напишите extends:
class UsersDataProvider extends \Paramonov\Grid\GridDataProvider

**Comment by xxxcoltxxx** [comment]
Вообще, на выходных опубликую новую версию с обновленным readme и примером. Пока что все новшевства в ветке dev-master

**Comment by borisovish** [comment]
Ок, буду ждать выходных.

**Comment by xxxcoltxxx** [comment]
Выпущена версия 2.0.0, следуйте инструкциям в [README](https://github.com/xxxcoltxxx/grid-laravel/blob/master/README.md). Так же можно посмотреть [исходники демо](https://github.com/xxxcoltxxx/grid-laravel-example) и [Демо](http://grid-laravel.colt-web.ru/)
