### ISSUE TITLE
Не работает функционал:

### ISSUE THREAD

**Issue by borisovish** [xxxcoltxxx/grid-laravel#16]
Есть еще два момента,  на которые хотел бы обратить внимание. 
Не работает вот этот функционал: 
            'cell' => "@{{ item.created_at | date:'dd.MM.yyyy HH:mm' }}",
также, не могу понять как вернуть в шаблоне значение: 
Я например хочу сделать вот так:
'active' => [
                        'title' => 'ВКЛ',
                        'type' => 'string',
                        'cell' => ("@{{ item.active }}")?"Вкл":"Вык",
                    ],
Ну или через blade @if.   Ну я думаю идея понятна ... 
Как это сделать ? 
буду благодарен за подстказку...

**Comment by xxxcoltxxx** [comment]
> Не работает вот этот функционал: 
> 'cell' => "@{{ item.created_at | date:'dd.MM.yyyy HH:mm' }}"

Во второй версии для форматирования дат не нужно прописывать `cell`. Вместо этого в вашем `DataProvider` должны быть методы `dates`, который возвращает массив колонок типа дат и `dateFormat`, которые возвращает необходимый формат даты

``` php
    /**
     * Необязательный метод
     * Поля типа "Дата"
     *
     * @return array
     */
    protected function dates()
    {
        return ['created_at', 'updated_at'];
    }

    /**
     * Необязательный метод
     * Фильтры по-умолчанию
     * Они применяются, если фильтры отсутствуют или пользователь сбросил все фильтры
     *
     * @return array
     */
    protected function dateFormat()
    {
        return 'd.m.Y в H:i:s';
    }
```

К слову, `cell` - это Angular-выражение, в него в вашем примере передавалась строка, а ему требуется timestamp

> также, не могу понять как вернуть в шаблоне значение: 
> Я например хочу сделать вот так:
> 'active' => [
> 'title' => 'ВКЛ',
> 'type' => 'string',
> 'cell' => ("@{{ item.active }}")?"Вкл":"Вык",
> ],
> Ну или через blade @if. Ну я думаю идея понятна ... 
> Как это сделать ? 
> буду благодарен за подстказку...

Есть 2 варианта сделать это - на angular и с помощью шаблона blade для рендеринга ячеек.
На Angular нужно просто прописать в cell `'cell' => "@{{ item.active ? 'Вкл', 'Выкл' }}"`. Возможно, нужно сделать проверку `@{{ item.active == '1' ? 'Вкл', 'Выкл' }}`, нужно смотреть что приходит - строка, bool или число.
А `type` лучше поставить в select и в `options` прописать ['Выкл', 'Вкл']. Так логичнее, что ли.
Второй вариант - вам нужно создать шаблон blade, описать там вашу ячейку и указать имя этого шаблона параметром в getData:
`/path/to/template.blade.php`

``` blade
@section('active')
    {{ $item->active ? 'Вкл' : 'Выкл' }}
@stop
```

`/path/to/controller.php`

``` php
    public function gridData()
    {
        $grid = new GridTable(new UsersDataProvider());
        return $grid->getData('users.grid.cells');
    }
```

**Comment by borisovish** [comment]
Запустил версию 2.0, все отлично все работает. Благодарю. 
Еще один маленький вопросик или даже скорее предложение по доработке: 
Хотелось бы иметь возможность  делать пустые колонки (не существующие в БД) в которые будут заполнены например какими либо кнопками, проще показать: http://joxi.ru/L21Ro4ns6LlE4A
в примере я это реализовал просто добавив отдельный шаблон в cells.blade.php но хотелось бы через файл вида,  что-то на подобии:
`
$grid->render(array(

```
                'NULL' => [
                    'title' => '',
                    'type' => 'NULL',
                    'class' => 'col-lg-1'
                   'cell' =>   "<a href="{{URL::current()}}/edit/@{{ item.id }}" role="button" class="btn-primary btn-xs"><i class="fa fa-edit"></i></a>", 
                ],
```

`
Идея думаю понятна, если сложно то не сильно "горит"... 
Заранее благодарю за ответ.

**Comment by borisovish** [comment]
Кстати для информации (возможно кто будет в коментариях искать) Ваш клас прекрасно сочитается вот с этой штукой https://github.com/kristijanhusak/laravel-form-builder. Получается полный функционал - удобный поиск + редактирование. 
Я раньше на jqgrid сидел, поиск редактирование все есть, но эго свести с Laravel те ещо карусели ... Да и с bootstrap постоянно потом вылезают проблемы...  Давно ищу альтернативу.

**Comment by xxxcoltxxx** [comment]
``` php
'tools' => [
    'title' => 'Инструменты',
    'class' => 'col-lg-1'
    'cell' => "<a href="{{URL::current()}}/edit/@{{ item.id }}" role="button" class="btn-primary btn-xs"><i class="fa fa-edit"></i></a>", 
],
```

Так должно работать

**Comment by borisovish** [comment]
Нет, не срабатывает - просто игнорирует этот масив и все ...

**Comment by xxxcoltxxx** [comment]
``` php
'tools' => [
    'title' => 'Инструменты',
    'sortable' => false,
    'default_column' => true,
    'class' => 'col-lg-1'
    'cell' => "<a href="{{URL::current()}}/edit/@{{ item.id }}" role="button" class="btn-primary btn-xs"><i class="fa fa-edit"></i></a>", 
],
```

А так?

**Comment by xxxcoltxxx** [comment]
За [kristijanhusak/laravel-form-builder](kristijanhusak/laravel-form-builder) спасибо, посмотрю =)

**Comment by borisovish** [comment]
Вот так заводится 
           'id' => [
                        'title' => 'Инструменты',
                        'sortable' => false,
                        'default_column' => true,
                        'class' => 'col-lg-1',
                        'cell' => "<a href='{{URL::current()}}/edit/@{{ item.id }}'' role='button' class='btn-primary btn-xs'><i class='fa fa-edit'></i></a>",
                    ],

в качестве ключа должно стоять реально существующее поля, а так как поля tools у меня в БД нету то оно игнорируется... 
Собственно это допустимо...

**Comment by xxxcoltxxx** [comment]
В качестве ключа может быть любое значение. Это просто алиас. Для него можно прописать свою фильтрацию и даже задать сортировку с помощью поля $sorting_resolve. У меня работает вот так:

``` php
'tools' => [
    'title' => 'Инструменты',
    'sortable' => false,
    'default_column' => true,
    'class' => 'col-lg-1',
    'cell' => "<a ng-href='@{{ location.pathname }}/edit/@{{ item.id }}' role='button' class='btn-primary btn-xs'><i class='fa fa-edit'></i></a>"
],
```

![image](https://cloud.githubusercontent.com/assets/5069097/13739300/74b1b4d2-e9db-11e5-87b0-5fe78015d0f7.png)

**Comment by xxxcoltxxx** [comment]
Попробуйте очистить куки

**Comment by borisovish** [comment]
Да, действительно очистка куки помогла. 
Спасибо- все работает...
